spring:
  datasource:
    url: jdbc:mysql://localhost:3306/management
    username: root
    password: h01642483324
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  messages:
    basename: static/messages

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

jwt:
  secret: spring-boot-jwt-authentication
  lifetime: 7200  # 2 hours